[project]
name = "keel-ds"
version = "0.2.5"
description = "KeelDS is a package to load some datasets from KEEL repository with some normalizations and with split and discretization options."
authors = [
    {name = "Maicondalllg", email = "maicon.dallagnol@unesp.br"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.26,<2",
    "pandas>=2.1,<3.0",
    "scikit-learn>=1.5,<1.6",
    "mdlp-discretization @ git+https://github.com/maicondallg/mdlp-discretization.git@old-version",
]

# Added GitHub project information
[project.urls]
Repository = "https://github.com/maicondallg/KeelDS"
Homepage = "https://github.com/maicondallg/KeelDS"
Documentation = "https://github.com/maicondallg/KeelDS#readme"


[tool.uv]
build-constraint-dependencies = [
    "numpy<2",
]


[build-system]
requires = ["meson-python>=0.14.0", "meson>=0.64.0", "wheel", "setuptools"]
build-backend = "mesonpy"
